package com.davoleo.testmod.config;

import net.minecraftforge.common.ForgeConfigSpec;

/*************************************************
 * Author: Davoleo
 * Date / Hour: 06/02/2019 / 18:19
 * Class: GeneratorConfig
 * Project: Test_mod
 * Copyright - © - Davoleo - 2019
 **************************************************/

public class GeneratorConfig {

    public static ForgeConfigSpec.IntValue MAX_POWER;
    public static ForgeConfigSpec.DoubleValue POWER_DAMAGE_FACTOR;

    public static void init(final ForgeConfigSpec.Builder SERVER_BUILDER, final ForgeConfigSpec.Builder CLIENT_BUILDER) {
        SERVER_BUILDER.comment("Generator");
        //CLIENT_BUILDER.comment("Generator");

        MAX_POWER = SERVER_BUILDER
                .comment("The maximum amount of power the generator can store")
                .defineInRange("generator.maxPower", 100000,  1, 1000000000);
        POWER_DAMAGE_FACTOR = SERVER_BUILDER
                .comment("Factor to control how much power is generated by one damage")
                .defineInRange("generator.powerDamageFactor", 5, 0.1, 10);
    }

}
